name: Check firmware update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - model: "SCG15"
            csc: "KDI"
          - model: "SCG21"
            csc: "KDI"
          - model: "SCG27"
            csc: "KDI"
          - model: "SC-53C"
            csc: "DCM"
          - model: "SC-53D"
            csc: "DCM"
          - model: "SC-53E"
            csc: "DCM"
          - model: "SM-A146B"
            csc: "INS"
          - model: "SM-A146M"
            csc: "ZTO"
          - model: "SM-A1660"
            csc: "BRI"
          - model: "SM-A1660"
            csc: "TGY"
          - model: "SM-A166B"
            csc: "EUX"
          - model: "SM-A166E"
            csc: "MID"
          - model: "SM-A166M"
            csc: "ARO"
          - model: "SM-A166M"
            csc: "TPA"
          - model: "SM-A166M"
            csc: "ZTO"
          - model: "SM-A176B"
            csc: "EUX"
          - model: "SM-A2560"
            csc: "TGY"
          - model: "SM-A256B"
            csc: "EUX"
          - model: "SM-A256E"
            csc: "EGY"
          - model: "SM-A256E"
            csc: "XNZ"
          - model: "SM-A256E"
            csc: "INS"
          - model: "SM-A256E"
            csc: "TPA"
          - model: "SM-A256E"
            csc: "XID"
          - model: "SM-A256N"
            csc: "KOO"
          - model: "SM-A266B"
            csc: "EUX"
          - model: "SM-A266M"
            csc: "ARO"
          - model: "SM-A266M"
            csc: "TPA"
          - model: "SM-A266M"
            csc: "ZTO"
          - model: "SM-A266U"
            csc: "CCT"
          - model: "SM-A266U"
            csc: "USC"
          - model: "SM-A266U1"
            csc: "XAG"
          - model: "SM-A266U1"
            csc: "VZW"
          - model: "SM-A3360"
            csc: "TGY"
          - model: "SM-A336B"
            csc: "EUX"
          - model: "SM-A336E"
            csc: "THL"
          - model: "SM-A336E"
            csc: "INS"
          - model: "SM-A336M"
            csc: "ARO"
          - model: "SM-A336M"
            csc: "GTO"
          - model: "SM-A336M"
            csc: "TPA"
          - model: "SM-A336M"
            csc: "ZTO"
          - model: "SM-A336N"
            csc: "KOO"
          - model: "SM-A356B"
            csc: "EUX"
          - model: "SM-A356E"
            csc: "INS"
          - model: "SM-A356E"
            csc: "TPA"
          - model: "SM-A376B"
            csc: "EUX"
          - model: "SM-A376E"
            csc: "INS"
          - model: "SM-A376U"
            csc: "ATT"
          - model: "SM-A376U1"
            csc: "ATT"
          - model: "SM-A5360"
            csc: "BRI"
          - model: "SM-A5360"
            csc: "CHC"
          - model: "SM-A5360"
            csc: "TGY"
          - model: "SM-A536B"
            csc: "EUX"
          - model: "SM-A536B"
            csc: "VIP"
          - model: "SM-A536E"
            csc: "INS"
          - model: "SM-A536E"
            csc: "PGU"
          - model: "SM-A536E"
            csc: "TPA"
          - model: "SM-A536N"
            csc: "KOO"
          - model: "SM-A536U1"
            csc: "ATC"
          - model: "SM-A536U1"
            csc: "PCT"
          - model: "SM-A536W"
            csc: "TBT"
          - model: "SM-A5460"
            csc: "BRI"
          - model: "SM-A5460"
            csc: "CHC"
          - model: "SM-A546B"
            csc: "EUX"
          - model: "SM-A546E"
            csc: "EGY"
          - model: "SM-A546E"
            csc: "INS"
          - model: "SM-A546E"
            csc: "PEO"
          - model: "SM-A546E"
            csc: "SEK"
          - model: "SM-A546E"
            csc: "TPA"
          - model: "SM-A546E"
            csc: "XID"
          - model: "SM-A546E"
            csc: "XSA"
          - model: "SM-A546E"
            csc: "ZTO"
          - model: "SM-A546S"
            csc: "SKC"
          - model: "SM-A546U"
            csc: "USC"
          - model: "SM-A546U1"
            csc: "XAA"
          - model: "SM-A546U1"
            csc: "VZW"
          - model: "SM-A546W"
            csc: "XAC"
          - model: "SM-A5560"
            csc: "CHC"
          - model: "SM-A556B"
            csc: "EUX"
          - model: "SM-A556E"
            csc: "INS"
          - model: "SM-A556E"
            csc: "TPA"
          - model: "SM-A556E"
            csc: "PGU"
          - model: "SM-A556S"
            csc: "SKC"
          - model: "SM-A5660"
            csc: "TGY"
          - model: "SM-A566B"
            csc: "EUX"
          - model: "SM-A566E"
            csc: "INS"
          - model: "SM-A566S"
            csc: "SKC"
          - model: "SM-A566W"
            csc: "XAC"
          - model: "SM-A5760"
            csc: "CHC"
          - model: "SM-A5760"
            csc: "TGY"
          - model: "SM-A576B"
            csc: "EUX"
          - model: "SM-A576W"
            csc: "BMC"
          - model: "SM-A576U1"
            csc: "ATT"
          - model: "SM-A576W"
            csc: "XAC"
          - model: "SM-E146B"
            csc: "INS"
          - model: "SM-E346B"
            csc: "INS"
          - model: "SM-E546B"
            csc: "INS"
          - model: "SM-E546B"
            csc: "NPB"
          - model: "SM-E546B"
            csc: "SLI"
          - model: "SM-F761B"
            csc: "EUX"
          - model: "SM-F7660"
            csc: "BRI"
          - model: "SM-F7660"
            csc: "CHC"
          - model: "SM-F7660"
            csc: "TGY"
          - model: "SM-F766B"
            csc: "EUX"
          - model: "SM-F766N"
            csc: "KOO"
          - model: "SM-F766Q"
            csc: "SJP"
          - model: "SM-F766U"
            csc: "ATT"
          - model: "SM-F766U"
            csc: "TMB"
          - model: "SM-F766U1"
            csc: "ATT"
          - model: "SM-F766U1"
            csc: "TMB"
          - model: "SM-F766W"
            csc: "BMC"
          - model: "SM-F766W"
            csc: "BWA"
          - model: "SM-F766Z"
            csc: "SBM"
          - model: "SM-G780F"
            csc: "XEO"
          - model: "SM-G990E"
            csc: "THL"
          - model: "SM-G990E"
            csc: "TPA"
          - model: "SM-G980F"
            csc: "XEO"
          - model: "SM-G981B"
            csc: "XEO"
          - model: "SM-G985F"
            csc: "XEO"
          - model: "SM-G986B"
            csc: "XEO"
          - model: "SM-G988B"
            csc: "XEO"
          - model: "SM-G991B"
            csc: "XEO"
          - model: "SM-G991B"
            csc: "XXV"
          - model: "SM-G991N"
            csc: "KOO"
          - model: "SM-G996B"
            csc: "XEO"
          - model: "SM-G996B"
            csc: "XXV"
          - model: "SM-G996N"
            csc: "KOO"
          - model: "SM-G998B"
            csc: "XEO"
          - model: "SM-G998B"
            csc: "XXV"
          - model: "SM-G998N"
            csc: "KOO"
          - model: "SM-M146B"
            csc: "INS"
          - model: "SM-M146B"
            csc: "SER"
          - model: "SM-M146B"
            csc: "ZTO"
          - model: "SM-M336B"
            csc: "EUX"
          - model: "SM-M336BU"
            csc: "INS"
          - model: "SM-M336K"
            csc: "KTC"
          - model: "SM-M346B1"
            csc: "XEO"
          - model: "SM-M346B1"
            csc: "XID"
          - model: "SM-M346B1"
            csc: "XXV"
          - model: "SM-M346B2"
            csc: "BRI"
          - model: "SM-M346B2"
            csc: "EGY"
          - model: "SM-M346B2"
            csc: "TGY"
          - model: "SM-M346B2"
            csc: "TUR"
          - model: "SM-M346B"
            csc: "INS"
          - model: "SM-M346B"
            csc: "ZTO"
          - model: "SM-M356B"
            csc: "INS"
          - model: "SM-M366B"
            csc: "INS"
          - model: "SM-M566B"
            csc: "INS"
          - model: "SM-N981B"
            csc: "XEO"
          - model: "SM-N986B"
            csc: "XEO"
          - model: "SM-P620"
            csc: "EUX"
            wifi: true
          - model: "SM-P625"
            csc: "EUX"
          - model: "SM-S711B"
            csc: "EUX"
          - model: "SM-S711N"
            csc: "KOO"
          - model: "SM-S721B"
            csc: "EUX"
          - model: "SM-S721N"
            csc: "KOO"
          - model: "SM-S731B"
            csc: "EUX"
          - model: "SM-S731N"
            csc: "KOO"
          - model: "SM-S901B"
            csc: "EUX"
          - model: "SM-S906B"
            csc: "EUX"
          - model: "SM-S908B"
            csc: "EUX"
          - model: "SM-S921B"
            csc: "EUX"
          - model: "SM-S921N"
            csc: "KOO"
          - model: "SM-S926B"
            csc: "EUX"
          - model: "SM-S926N"
            csc: "KOO"
          - model: "SM-S942B"
            csc: "EUX"
          - model: "SM-S947B"
            csc: "EUX"
          - model: "SM-X520"
            csc: "EUX"
            wifi: true
          - model: "SM-X520"
            csc: "ZBR"
            wifi: true
          - model: "SM-X526B"
            csc: "EUX"
          - model: "SM-X616B"
            csc: "EUX"
          - model: "SM-X620"
            csc: "EUX"
            wifi: true

    concurrency:
      group: "update-${{ matrix.model }}-${{ matrix.csc }}-${{ github.ref }}"
      cancel-in-progress: true
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -y rsync liblz4-tool zip android-sdk-libsparse-utils f2fs-tools linux-modules-extra-$(uname -r) python3 unzip > /dev/null
          sudo modprobe f2fs
          pip3 install git+https://github.com/ducthoe/samfwdl.git > /dev/null

      - name: Fetch firmware
      - name: Run merged firmware update
        env:
          MODEL: ${{ matrix.model }}
          CSC: ${{ matrix.csc }}
          IS_WIFI: ${{ matrix.wifi }}
          GHR: ${{ github.ref }}
        run: |
          ./scripts/check.sh || exit 1

      - name: Push changes to repo
        if: env.update == 1
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload release assets
        if: env.update == 1
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: versions.txt
          tag_name: "${{ env.latest_shortversion }}_${{ matrix.csc }}_${{ env.omc }}"
          name: "${{ env.latest_shortversion }} - ${{ matrix.model }} - ${{ matrix.csc }} - ${{ env.omc }}"
          files: |
            ${{ env.bl_tar }}
            ${{ env.cp_tar }}
            ${{ env.home_csc_tar }}
            ${{ env.latest_shortversion }}_kernel.tar
            ${{ env.pit_file }}
            ${{ env.latest_shortversion }}_patched_vbmeta.tar
            ${{ env.latest_shortversion }}_product.zip
            ${{ env.latest_shortversion }}_vendor.zip
            ${{ env.latest_shortversion }}_vendor-extracted.zip
            ${{ env.latest_shortversion }}_firmware_tee.zip
            ${{ env.latest_shortversion}}_vendor.prop
