name: Check firmware update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - model: "SCG15"
            csc: "KDI"
          - model: "SCG21"
            csc: "KDI"
          - model: "SCG27"
            csc: "KDI"
          - model: "SC-53C"
            csc: "DCM"
          - model: "SC-53D"
            csc: "DCM"
          - model: "SC-53E"
            csc: "DCM"
          - model: "SM-A146B"
            csc: "INS"
          - model: "SM-A146M"
            csc: "ZTO"
          - model: "SM-A1660"
            csc: "BRI"
          - model: "SM-A1660"
            csc: "TGY"
          - model: "SM-A166B"
            csc: "EUX"
          - model: "SM-A166E"
            csc: "MID"
          - model: "SM-A166M"
            csc: "ARO"
          - model: "SM-A166M"
            csc: "TPA"
          - model: "SM-A166M"
            csc: "ZTO"
          - model: "SM-A176B"
            csc: "EUX"
          - model: "SM-A2560"
            csc: "TGY"
          - model: "SM-A256B"
            csc: "EUX"
          - model: "SM-A256E"
            csc: "EGY"
          - model: "SM-A256E"
            csc: "XNZ"
          - model: "SM-A256E"
            csc: "INS"
          - model: "SM-A256E"
            csc: "TPA"
          - model: "SM-A256E"
            csc: "XID"
          - model: "SM-A256N"
            csc: "KOO"
          - model: "SM-A266B"
            csc: "EUX"
          - model: "SM-A266M"
            csc: "ARO"
          - model: "SM-A266M"
            csc: "TPA"
          - model: "SM-A266M"
            csc: "ZTO"
          - model: "SM-A3360"
            csc: "TGY"
          - model: "SM-A336B"
            csc: "EUX"
          - model: "SM-A336E"
            csc: "THL"
          - model: "SM-A336E"
            csc: "INS"
          - model: "SM-A336M"
            csc: "ARO"
          - model: "SM-A336M"
            csc: "GTO"
          - model: "SM-A336M"
            csc: "TPA"
          - model: "SM-A336M"
            csc: "ZTO"
          - model: "SM-A336N"
            csc: "KOO"
          - model: "SM-A356B"
            csc: "EUX"
          - model: "SM-A356E"
            csc: "INS"
          - model: "SM-A356E"
            csc: "TPA"
          - model: "SM-A5360"
            csc: "BRI"
          - model: "SM-A5360"
            csc: "CHC"
          - model: "SM-A5360"
            csc: "TGY"
          - model: "SM-A536B"
            csc: "EUX"
          - model: "SM-A536B"
            csc: "VIP"
          - model: "SM-A536E"
            csc: "INS"
          - model: "SM-A536E"
            csc: "PGU"
          - model: "SM-A536E"
            csc: "TPA"
          - model: "SM-A536N"
            csc: "KOO"
          - model: "SM-A536U1"
            csc: "ATC"
          - model: "SM-A536U1"
            csc: "PCT"
          - model: "SM-A536W"
            csc: "TBT"
          - model: "SM-A5460"
            csc: "BRI"
          - model: "SM-A5460"
            csc: "CHC"
          - model: "SM-A546B"
            csc: "EUX"
          - model: "SM-A546E"
            csc: "EGY"
          - model: "SM-A546E"
            csc: "INS"
          - model: "SM-A546E"
            csc: "PEO"
          - model: "SM-A546E"
            csc: "SEK"
          - model: "SM-A546E"
            csc: "TPA"
          - model: "SM-A546E"
            csc: "XID"
          - model: "SM-A546E"
            csc: "XSA"
          - model: "SM-A546E"
            csc: "ZTO"
          - model: "SM-A546S"
            csc: "SKC"
          - model: "SM-A5560"
            csc: "CHC"
          - model: "SM-A556B"
            csc: "EUX"
          - model: "SM-A556E"
            csc: "INS"
          - model: "SM-A556E"
            csc: "TPA"
          - model: "SM-A556E"
            csc: "PGU"
          - model: "SM-A556S"
            csc: "SKC"
          - model: "SM-A5660"
            csc: "TGY"
          - model: "SM-A566B"
            csc: "EUX"
          - model: "SM-A566E"
            csc: "INS"
          - model: "SM-A566S"
            csc: "SKC"
          - model: "SM-A566W"
            csc: "XAC"
          - model: "SM-E146B"
            csc: "INS"
          - model: "SM-E346B"
            csc: "INS"
          - model: "SM-G780F"
            csc: "XEO"
          - model: "SM-G990E"
            csc: "THL"
          - model: "SM-G990E"
            csc: "TPA"
          - model: "SM-G980F"
            csc: "XEO"
          - model: "SM-G981B"
            csc: "XEO"
          - model: "SM-G985F"
            csc: "XEO"
          - model: "SM-G986B"
            csc: "XEO"
          - model: "SM-G988B"
            csc: "XEO"
          - model: "SM-G991B"
            csc: "XEO"
          - model: "SM-G991B"
            csc: "XXV"
          - model: "SM-G991N"
            csc: "KOO"
          - model: "SM-G996B"
            csc: "XEO"
          - model: "SM-G996B"
            csc: "XXV"
          - model: "SM-G996N"
            csc: "KOO"
          - model: "SM-G998B"
            csc: "XEO"
          - model: "SM-G998B"
            csc: "XXV"
          - model: "SM-G998N"
            csc: "KOO"
          - model: "SM-M146B"
            csc: "INS"
          - model: "SM-M146B"
            csc: "SER"
          - model: "SM-M146B"
            csc: "ZTO"
          - model: "SM-M336B"
            csc: "EUX"
          - model: "SM-M336BU"
            csc: "INS"
          - model: "SM-M336K"
            csc: "KTC"
          - model: "SM-M346B1"
            csc: "XEO"
          - model: "SM-M346B1"
            csc: "XID"
          - model: "SM-M346B1"
            csc: "XXV"
          - model: "SM-M346B2"
            csc: "BRI"
          - model: "SM-M346B2"
            csc: "EGY"
          - model: "SM-M346B2"
            csc: "TGY"
          - model: "SM-M346B2"
            csc: "TUR"
          - model: "SM-M346B"
            csc: "INS"
          - model: "SM-M346B"
            csc: "ZTO"
          - model: "SM-M356B"
            csc: "INS"
          - model: "SM-M366B"
            csc: "INS"
          - model: "SM-M566B"
            csc: "INS"
          - model: "SM-N981B"
            csc: "XEO"
          - model: "SM-N986B"
            csc: "XEO"
          - model: "SM-P620"
            csc: "EUX"
          - model: "SM-P625"
            csc: "EUX"
          - model: "SM-S901B"
            csc: "EUX"
          - model: "SM-S906B"
            csc: "EUX"
          - model: "SM-S908B"
            csc: "EUX"
          - model: "SM-X520"
            csc: "EUX"
          - model: "SM-X520"
            csc: "ZBR"
          - model: "SM-X526B"
            csc: "EUX"
          - model: "SM-X616B"
            csc: "EUX"
          - model: "SM-X620"
            csc: "EUX"

    concurrency:
      group: "update-${{ matrix.model }}-${{ matrix.csc }}-${{ github.ref }}"
      cancel-in-progress: true
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compare latest version with current version
        env:
          MODEL: ${{ matrix.model }}
          CSC: ${{ matrix.csc }}
        run: |
          ./scripts/compare_firmware.sh

      - name: Cleanup space (1/2)
        if: env.update == 1
        run: |
          sudo apt-get remove --purge -y "php*" "dotnet*" "mysql*" "nodejs*" "clang*" "google*"
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo docker image prune --all --force
          sudo docker builder prune -a
          sudo rm -rf /usr/share/dotnet /usr/local /opt/ghc /opt/hostedtoolcache/CodeQL

      - name: Install dependencies
        if: env.update == 1
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync liblz4-tool zip android-sdk-libsparse-utils f2fs-tools linux-modules-extra-$(uname -r) python3 python3-venv unzip gh
          sudo modprobe f2fs

      - name: Get firmware
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          CSC: ${{ matrix.csc }}
        run: |
          ./scripts/fetch_firmware.sh

      - name: Get path of files
        if: env.update == 1
        run: |
          ./scripts/get_path.sh

      - name: Cleanup space (2/3)
        if: env.update == 1
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Cleanup space (2/3)
        if: env.update == 1
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Set Swap Space
        if: env.update == 1
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 20

      - name: Extract PIT file
        if: env.update == 1
        run: |
          tar --wildcards --exclude='*/*' -xvf ${{ env.csc_tar }} '*.pit'
          echo "pit_file=`find -name *.pit`" >> $GITHUB_ENV

      - name: Generate patched vbmeta
        if: env.update == 1
        env:
          AP_TAR: ${{ env.ap_tar }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/vbmeta.sh

      - name: Extract partitions
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          AP_TAR: ${{ env.ap_tar }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/partitions.sh

      - name: Extract kernel images
        if: env.update == 1
        env:
          AP_TAR: ${{ env.ap_tar }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/kernel.sh

      - name: Get some blobs
        if: env.update == 1
        env:
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/blobs.sh
           
      - name: Generate proprietary-files.txt
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          OMC: ${{ env.omc }}
          CSC: ${{ matrix.csc }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/proprietary-files.sh

      - name: Generate proprietary-firmware.txt
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          OMC: ${{ env.omc }}
          CSC: ${{ matrix.csc }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
          BL_TAR: ${{ env.bl_tar }}
          CP_TAR: ${{ env.cp_tar }}
        run: |
          ./scripts/proprietary-firmware.sh

      - name: Generate file_context
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          CSC: ${{ matrix.csc }}
          OMC: ${{ env.omc }}
        run: |
          ./scripts/file_context.sh
      
      - name: Generate fs_config
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          CSC: ${{ matrix.csc }}
          OMC: ${{ env.omc }}
        run: |
          ./scripts/fs_config.sh

      - name: AOSP Dump
        if: env.update == 1
        env:
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/dump.sh

      - name: Generate versions.txt
        if: env.update == 1
        env:
          AP_TAR: ${{ env.ap_tar }}
          BL_LOCK: ${{ env.bl_lock }}
          CSC_TAR: ${{ env.csc_tar }}
          MODEL: ${{ matrix.model }}
          CSC: ${{ matrix.csc }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
          LATEST_CSCVERSION: ${{ env.latest_cscversion }}
        run: |
          ./scripts/versions.sh

      - name: Update current version
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          OMC: ${{ env.omc }}
          CSC: ${{ matrix.csc }}
          LATEST_VERSION: ${{ env.latest_version }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
          GHF: ${{ github.ref }}
        run: |
          sudo apt install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          ./scripts/git.sh

      - name: Push changes to repo
        if: env.update == 1
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload release assets
        if: env.update == 1
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: versions.txt
          tag_name: "${{ env.latest_shortversion }}_${{ matrix.csc }}_${{ env.omc }}"
          name: "${{ env.latest_shortversion }} - ${{ matrix.model }} - ${{ matrix.csc }} - ${{ env.omc }}"
          files: |
            ${{ env.bl_tar }}
            ${{ env.cp_tar }}
            ${{ env.home_csc_tar }}
            ${{ env.latest_shortversion }}_kernel.tar
            ${{ env.pit_file }}
            ${{ env.latest_shortversion }}_patched_vbmeta.tar
            ${{ env.latest_shortversion }}_dump-AOSP.zip
            ${{ env.latest_shortversion }}_product.zip
            ${{ env.latest_shortversion }}_vendor.zip
            ${{ env.latest_shortversion }}_vendor-extracted.zip
            ${{ env.latest_shortversion }}_firmware_tee.zip
            ${{ env.latest_shortversion }}_BL_CP-los.zip
            ${{ env.latest_shortversion}}_vendor.prop
